name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Leptos
      run: cargo install cargo-leptos
    - name: Add wasm32-unknown-unknown target
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: cargo leptos build --release
    - name: Run tests
      run: cargo test --verbose
  build-container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Image
      run: docker build -t alexohneander/alexohneander-rust:latest .
    - name: Push Image
      run: docker push alexohneander/alexohneander-rust:latest
